# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info
if version_info >= (3,0,0):
    new_instancemethod = lambda func, inst, cls: _capi.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_capi', [dirname(__file__)])
        except ImportError:
            import _capi
            return _capi
        if fp is not None:
            try:
                _mod = imp.load_module('_capi', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _capi = swig_import_helper()
    del swig_import_helper
else:
    import _capi
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr



def link2obj(*args):
  return _capi.link2obj(*args)
link2obj = _capi.link2obj

def obj2link(*args):
  return _capi.obj2link(*args)
obj2link = _capi.obj2link

def get_from_kernel(*args):
  return _capi.get_from_kernel(*args)
get_from_kernel = _capi.get_from_kernel

def inet_get_conf(*args):
  return _capi.inet_get_conf(*args)
inet_get_conf = _capi.inet_get_conf

def rtnl_scope2str(*args):
  return _capi.rtnl_scope2str(*args)
rtnl_scope2str = _capi.rtnl_scope2str

def rtnl_str2scope(*args):
  return _capi.rtnl_str2scope(*args)
rtnl_str2scope = _capi.rtnl_str2scope

def rtnl_link_alloc():
  return _capi.rtnl_link_alloc()
rtnl_link_alloc = _capi.rtnl_link_alloc

def rtnl_link_get(*args):
  return _capi.rtnl_link_get(*args)
rtnl_link_get = _capi.rtnl_link_get

def rtnl_link_get_by_name(*args):
  return _capi.rtnl_link_get_by_name(*args)
rtnl_link_get_by_name = _capi.rtnl_link_get_by_name

def rtnl_link_build_add_request(*args):
  return _capi.rtnl_link_build_add_request(*args)
rtnl_link_build_add_request = _capi.rtnl_link_build_add_request

def rtnl_link_add(*args):
  return _capi.rtnl_link_add(*args)
rtnl_link_add = _capi.rtnl_link_add

def rtnl_link_build_change_request(*args):
  return _capi.rtnl_link_build_change_request(*args)
rtnl_link_build_change_request = _capi.rtnl_link_build_change_request

def rtnl_link_change(*args):
  return _capi.rtnl_link_change(*args)
rtnl_link_change = _capi.rtnl_link_change

def rtnl_link_build_delete_request(*args):
  return _capi.rtnl_link_build_delete_request(*args)
rtnl_link_build_delete_request = _capi.rtnl_link_build_delete_request

def rtnl_link_delete(*args):
  return _capi.rtnl_link_delete(*args)
rtnl_link_delete = _capi.rtnl_link_delete

def rtnl_link_build_get_request(*args):
  return _capi.rtnl_link_build_get_request(*args)
rtnl_link_build_get_request = _capi.rtnl_link_build_get_request

def rtnl_link_stat2str(*args):
  return _capi.rtnl_link_stat2str(*args)
rtnl_link_stat2str = _capi.rtnl_link_stat2str

def rtnl_link_str2stat(*args):
  return _capi.rtnl_link_str2stat(*args)
rtnl_link_str2stat = _capi.rtnl_link_str2stat

def rtnl_link_flags2str(*args):
  return _capi.rtnl_link_flags2str(*args)
rtnl_link_flags2str = _capi.rtnl_link_flags2str

def rtnl_link_str2flags(*args):
  return _capi.rtnl_link_str2flags(*args)
rtnl_link_str2flags = _capi.rtnl_link_str2flags

def rtnl_link_operstate2str(*args):
  return _capi.rtnl_link_operstate2str(*args)
rtnl_link_operstate2str = _capi.rtnl_link_operstate2str

def rtnl_link_str2operstate(*args):
  return _capi.rtnl_link_str2operstate(*args)
rtnl_link_str2operstate = _capi.rtnl_link_str2operstate

def rtnl_link_mode2str(*args):
  return _capi.rtnl_link_mode2str(*args)
rtnl_link_mode2str = _capi.rtnl_link_mode2str

def rtnl_link_str2mode(*args):
  return _capi.rtnl_link_str2mode(*args)
rtnl_link_str2mode = _capi.rtnl_link_str2mode

def rtnl_link_set_qdisc(*args):
  return _capi.rtnl_link_set_qdisc(*args)
rtnl_link_set_qdisc = _capi.rtnl_link_set_qdisc

def rtnl_link_get_qdisc(*args):
  return _capi.rtnl_link_get_qdisc(*args)
rtnl_link_get_qdisc = _capi.rtnl_link_get_qdisc

def rtnl_link_set_name(*args):
  return _capi.rtnl_link_set_name(*args)
rtnl_link_set_name = _capi.rtnl_link_set_name

def rtnl_link_get_name(*args):
  return _capi.rtnl_link_get_name(*args)
rtnl_link_get_name = _capi.rtnl_link_get_name

def rtnl_link_set_flags(*args):
  return _capi.rtnl_link_set_flags(*args)
rtnl_link_set_flags = _capi.rtnl_link_set_flags

def rtnl_link_unset_flags(*args):
  return _capi.rtnl_link_unset_flags(*args)
rtnl_link_unset_flags = _capi.rtnl_link_unset_flags

def rtnl_link_get_flags(*args):
  return _capi.rtnl_link_get_flags(*args)
rtnl_link_get_flags = _capi.rtnl_link_get_flags

def rtnl_link_set_mtu(*args):
  return _capi.rtnl_link_set_mtu(*args)
rtnl_link_set_mtu = _capi.rtnl_link_set_mtu

def rtnl_link_get_mtu(*args):
  return _capi.rtnl_link_get_mtu(*args)
rtnl_link_get_mtu = _capi.rtnl_link_get_mtu

def rtnl_link_set_txqlen(*args):
  return _capi.rtnl_link_set_txqlen(*args)
rtnl_link_set_txqlen = _capi.rtnl_link_set_txqlen

def rtnl_link_get_txqlen(*args):
  return _capi.rtnl_link_get_txqlen(*args)
rtnl_link_get_txqlen = _capi.rtnl_link_get_txqlen

def rtnl_link_set_weight(*args):
  return _capi.rtnl_link_set_weight(*args)
rtnl_link_set_weight = _capi.rtnl_link_set_weight

def rtnl_link_get_weight(*args):
  return _capi.rtnl_link_get_weight(*args)
rtnl_link_get_weight = _capi.rtnl_link_get_weight

def rtnl_link_set_ifindex(*args):
  return _capi.rtnl_link_set_ifindex(*args)
rtnl_link_set_ifindex = _capi.rtnl_link_set_ifindex

def rtnl_link_get_ifindex(*args):
  return _capi.rtnl_link_get_ifindex(*args)
rtnl_link_get_ifindex = _capi.rtnl_link_get_ifindex

def rtnl_link_set_family(*args):
  return _capi.rtnl_link_set_family(*args)
rtnl_link_set_family = _capi.rtnl_link_set_family

def rtnl_link_get_family(*args):
  return _capi.rtnl_link_get_family(*args)
rtnl_link_get_family = _capi.rtnl_link_get_family

def rtnl_link_set_arptype(*args):
  return _capi.rtnl_link_set_arptype(*args)
rtnl_link_set_arptype = _capi.rtnl_link_set_arptype

def rtnl_link_get_arptype(*args):
  return _capi.rtnl_link_get_arptype(*args)
rtnl_link_get_arptype = _capi.rtnl_link_get_arptype

def rtnl_link_set_addr(*args):
  return _capi.rtnl_link_set_addr(*args)
rtnl_link_set_addr = _capi.rtnl_link_set_addr

def rtnl_link_get_addr(*args):
  return _capi.rtnl_link_get_addr(*args)
rtnl_link_get_addr = _capi.rtnl_link_get_addr

def rtnl_link_set_broadcast(*args):
  return _capi.rtnl_link_set_broadcast(*args)
rtnl_link_set_broadcast = _capi.rtnl_link_set_broadcast

def rtnl_link_get_broadcast(*args):
  return _capi.rtnl_link_get_broadcast(*args)
rtnl_link_get_broadcast = _capi.rtnl_link_get_broadcast

def rtnl_link_set_link(*args):
  return _capi.rtnl_link_set_link(*args)
rtnl_link_set_link = _capi.rtnl_link_set_link

def rtnl_link_get_link(*args):
  return _capi.rtnl_link_get_link(*args)
rtnl_link_get_link = _capi.rtnl_link_get_link

def rtnl_link_set_master(*args):
  return _capi.rtnl_link_set_master(*args)
rtnl_link_set_master = _capi.rtnl_link_set_master

def rtnl_link_get_master(*args):
  return _capi.rtnl_link_get_master(*args)
rtnl_link_get_master = _capi.rtnl_link_get_master

def rtnl_link_set_operstate(*args):
  return _capi.rtnl_link_set_operstate(*args)
rtnl_link_set_operstate = _capi.rtnl_link_set_operstate

def rtnl_link_get_operstate(*args):
  return _capi.rtnl_link_get_operstate(*args)
rtnl_link_get_operstate = _capi.rtnl_link_get_operstate

def rtnl_link_set_linkmode(*args):
  return _capi.rtnl_link_set_linkmode(*args)
rtnl_link_set_linkmode = _capi.rtnl_link_set_linkmode

def rtnl_link_get_linkmode(*args):
  return _capi.rtnl_link_get_linkmode(*args)
rtnl_link_get_linkmode = _capi.rtnl_link_get_linkmode

def rtnl_link_get_ifalias(*args):
  return _capi.rtnl_link_get_ifalias(*args)
rtnl_link_get_ifalias = _capi.rtnl_link_get_ifalias

def rtnl_link_set_ifalias(*args):
  return _capi.rtnl_link_set_ifalias(*args)
rtnl_link_set_ifalias = _capi.rtnl_link_set_ifalias

def rtnl_link_get_num_vf(*args):
  return _capi.rtnl_link_get_num_vf(*args)
rtnl_link_get_num_vf = _capi.rtnl_link_get_num_vf

def rtnl_link_get_stat(*args):
  return _capi.rtnl_link_get_stat(*args)
rtnl_link_get_stat = _capi.rtnl_link_get_stat

def rtnl_link_set_stat(*args):
  return _capi.rtnl_link_set_stat(*args)
rtnl_link_set_stat = _capi.rtnl_link_set_stat

def rtnl_link_set_info_type(*args):
  return _capi.rtnl_link_set_info_type(*args)
rtnl_link_set_info_type = _capi.rtnl_link_set_info_type

def rtnl_link_get_info_type(*args):
  return _capi.rtnl_link_get_info_type(*args)
rtnl_link_get_info_type = _capi.rtnl_link_get_info_type
class vlan_map(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    vm_from = _swig_property(_capi.vlan_map_vm_from_get, _capi.vlan_map_vm_from_set)
    vm_to = _swig_property(_capi.vlan_map_vm_to_get, _capi.vlan_map_vm_to_set)
    __swig_destroy__ = _capi.delete_vlan_map
vlan_map_swigregister = _capi.vlan_map_swigregister
vlan_map_swigregister(vlan_map)

VLAN_PRIO_MAX = _capi.VLAN_PRIO_MAX

def rtnl_link_vlan_flags2str(*args):
  return _capi.rtnl_link_vlan_flags2str(*args)
rtnl_link_vlan_flags2str = _capi.rtnl_link_vlan_flags2str

def rtnl_link_vlan_str2flags(*args):
  return _capi.rtnl_link_vlan_str2flags(*args)
rtnl_link_vlan_str2flags = _capi.rtnl_link_vlan_str2flags

def rtnl_link_vlan_set_id(*args):
  return _capi.rtnl_link_vlan_set_id(*args)
rtnl_link_vlan_set_id = _capi.rtnl_link_vlan_set_id

def rtnl_link_vlan_get_id(*args):
  return _capi.rtnl_link_vlan_get_id(*args)
rtnl_link_vlan_get_id = _capi.rtnl_link_vlan_get_id

def rtnl_link_vlan_set_flags(*args):
  return _capi.rtnl_link_vlan_set_flags(*args)
rtnl_link_vlan_set_flags = _capi.rtnl_link_vlan_set_flags

def rtnl_link_vlan_unset_flags(*args):
  return _capi.rtnl_link_vlan_unset_flags(*args)
rtnl_link_vlan_unset_flags = _capi.rtnl_link_vlan_unset_flags

def rtnl_link_vlan_get_flags(*args):
  return _capi.rtnl_link_vlan_get_flags(*args)
rtnl_link_vlan_get_flags = _capi.rtnl_link_vlan_get_flags

def rtnl_link_vlan_set_ingress_map(*args):
  return _capi.rtnl_link_vlan_set_ingress_map(*args)
rtnl_link_vlan_set_ingress_map = _capi.rtnl_link_vlan_set_ingress_map

def rtnl_link_vlan_get_ingress_map(*args):
  return _capi.rtnl_link_vlan_get_ingress_map(*args)
rtnl_link_vlan_get_ingress_map = _capi.rtnl_link_vlan_get_ingress_map

def rtnl_link_vlan_set_egress_map(*args):
  return _capi.rtnl_link_vlan_set_egress_map(*args)
rtnl_link_vlan_set_egress_map = _capi.rtnl_link_vlan_set_egress_map

def rtnl_link_vlan_get_egress_map(*args):
  return _capi.rtnl_link_vlan_get_egress_map(*args)
rtnl_link_vlan_get_egress_map = _capi.rtnl_link_vlan_get_egress_map

def rtnl_link_inet_devconf2str(*args):
  return _capi.rtnl_link_inet_devconf2str(*args)
rtnl_link_inet_devconf2str = _capi.rtnl_link_inet_devconf2str

def rtnl_link_inet_str2devconf(*args):
  return _capi.rtnl_link_inet_str2devconf(*args)
rtnl_link_inet_str2devconf = _capi.rtnl_link_inet_str2devconf

def rtnl_link_inet_set_conf(*args):
  return _capi.rtnl_link_inet_set_conf(*args)
rtnl_link_inet_set_conf = _capi.rtnl_link_inet_set_conf

def tc_str2handle(*args):
  return _capi.tc_str2handle(*args)
tc_str2handle = _capi.tc_str2handle

def rtnl_tc_set_ifindex(*args):
  return _capi.rtnl_tc_set_ifindex(*args)
rtnl_tc_set_ifindex = _capi.rtnl_tc_set_ifindex

def rtnl_tc_get_ifindex(*args):
  return _capi.rtnl_tc_get_ifindex(*args)
rtnl_tc_get_ifindex = _capi.rtnl_tc_get_ifindex

def rtnl_tc_set_link(*args):
  return _capi.rtnl_tc_set_link(*args)
rtnl_tc_set_link = _capi.rtnl_tc_set_link

def rtnl_tc_get_link(*args):
  return _capi.rtnl_tc_get_link(*args)
rtnl_tc_get_link = _capi.rtnl_tc_get_link

def rtnl_tc_set_mtu(*args):
  return _capi.rtnl_tc_set_mtu(*args)
rtnl_tc_set_mtu = _capi.rtnl_tc_set_mtu

def rtnl_tc_get_mtu(*args):
  return _capi.rtnl_tc_get_mtu(*args)
rtnl_tc_get_mtu = _capi.rtnl_tc_get_mtu

def rtnl_tc_set_mpu(*args):
  return _capi.rtnl_tc_set_mpu(*args)
rtnl_tc_set_mpu = _capi.rtnl_tc_set_mpu

def rtnl_tc_get_mpu(*args):
  return _capi.rtnl_tc_get_mpu(*args)
rtnl_tc_get_mpu = _capi.rtnl_tc_get_mpu

def rtnl_tc_set_overhead(*args):
  return _capi.rtnl_tc_set_overhead(*args)
rtnl_tc_set_overhead = _capi.rtnl_tc_set_overhead

def rtnl_tc_get_overhead(*args):
  return _capi.rtnl_tc_get_overhead(*args)
rtnl_tc_get_overhead = _capi.rtnl_tc_get_overhead

def rtnl_tc_set_linktype(*args):
  return _capi.rtnl_tc_set_linktype(*args)
rtnl_tc_set_linktype = _capi.rtnl_tc_set_linktype

def rtnl_tc_get_linktype(*args):
  return _capi.rtnl_tc_get_linktype(*args)
rtnl_tc_get_linktype = _capi.rtnl_tc_get_linktype

def rtnl_tc_set_handle(*args):
  return _capi.rtnl_tc_set_handle(*args)
rtnl_tc_set_handle = _capi.rtnl_tc_set_handle

def rtnl_tc_get_handle(*args):
  return _capi.rtnl_tc_get_handle(*args)
rtnl_tc_get_handle = _capi.rtnl_tc_get_handle

def rtnl_tc_set_parent(*args):
  return _capi.rtnl_tc_set_parent(*args)
rtnl_tc_set_parent = _capi.rtnl_tc_set_parent

def rtnl_tc_get_parent(*args):
  return _capi.rtnl_tc_get_parent(*args)
rtnl_tc_get_parent = _capi.rtnl_tc_get_parent

def rtnl_tc_set_kind(*args):
  return _capi.rtnl_tc_set_kind(*args)
rtnl_tc_set_kind = _capi.rtnl_tc_set_kind

def rtnl_tc_get_kind(*args):
  return _capi.rtnl_tc_get_kind(*args)
rtnl_tc_get_kind = _capi.rtnl_tc_get_kind

def rtnl_tc_get_stat(*args):
  return _capi.rtnl_tc_get_stat(*args)
rtnl_tc_get_stat = _capi.rtnl_tc_get_stat

def rtnl_tc_calc_txtime(*args):
  return _capi.rtnl_tc_calc_txtime(*args)
rtnl_tc_calc_txtime = _capi.rtnl_tc_calc_txtime

def rtnl_tc_calc_bufsize(*args):
  return _capi.rtnl_tc_calc_bufsize(*args)
rtnl_tc_calc_bufsize = _capi.rtnl_tc_calc_bufsize

def rtnl_tc_calc_cell_log(*args):
  return _capi.rtnl_tc_calc_cell_log(*args)
rtnl_tc_calc_cell_log = _capi.rtnl_tc_calc_cell_log

def rtnl_tc_read_classid_file():
  return _capi.rtnl_tc_read_classid_file()
rtnl_tc_read_classid_file = _capi.rtnl_tc_read_classid_file

def rtnl_tc_handle2str(*args):
  return _capi.rtnl_tc_handle2str(*args)
rtnl_tc_handle2str = _capi.rtnl_tc_handle2str

def rtnl_classid_generate(*args):
  return _capi.rtnl_classid_generate(*args)
rtnl_classid_generate = _capi.rtnl_classid_generate

def qdisc2obj(*args):
  return _capi.qdisc2obj(*args)
qdisc2obj = _capi.qdisc2obj

def obj2qdisc(*args):
  return _capi.obj2qdisc(*args)
obj2qdisc = _capi.obj2qdisc

def class2obj(*args):
  return _capi.class2obj(*args)
class2obj = _capi.class2obj

def obj2class(*args):
  return _capi.obj2class(*args)
obj2class = _capi.obj2class

def cls2obj(*args):
  return _capi.cls2obj(*args)
cls2obj = _capi.cls2obj

def obj2cls(*args):
  return _capi.obj2cls(*args)
obj2cls = _capi.obj2cls

def obj2tc(*args):
  return _capi.obj2tc(*args)
obj2tc = _capi.obj2tc

def rtnl_qdisc_alloc():
  return _capi.rtnl_qdisc_alloc()
rtnl_qdisc_alloc = _capi.rtnl_qdisc_alloc

def rtnl_qdisc_get(*args):
  return _capi.rtnl_qdisc_get(*args)
rtnl_qdisc_get = _capi.rtnl_qdisc_get

def rtnl_qdisc_get_by_parent(*args):
  return _capi.rtnl_qdisc_get_by_parent(*args)
rtnl_qdisc_get_by_parent = _capi.rtnl_qdisc_get_by_parent

def rtnl_qdisc_build_add_request(*args):
  return _capi.rtnl_qdisc_build_add_request(*args)
rtnl_qdisc_build_add_request = _capi.rtnl_qdisc_build_add_request

def rtnl_qdisc_add(*args):
  return _capi.rtnl_qdisc_add(*args)
rtnl_qdisc_add = _capi.rtnl_qdisc_add

def rtnl_qdisc_build_update_request(*args):
  return _capi.rtnl_qdisc_build_update_request(*args)
rtnl_qdisc_build_update_request = _capi.rtnl_qdisc_build_update_request

def rtnl_qdisc_update(*args):
  return _capi.rtnl_qdisc_update(*args)
rtnl_qdisc_update = _capi.rtnl_qdisc_update

def rtnl_qdisc_build_delete_request(*args):
  return _capi.rtnl_qdisc_build_delete_request(*args)
rtnl_qdisc_build_delete_request = _capi.rtnl_qdisc_build_delete_request

def rtnl_qdisc_delete(*args):
  return _capi.rtnl_qdisc_delete(*args)
rtnl_qdisc_delete = _capi.rtnl_qdisc_delete

def rtnl_cls_alloc():
  return _capi.rtnl_cls_alloc()
rtnl_cls_alloc = _capi.rtnl_cls_alloc

def rtnl_cls_put(*args):
  return _capi.rtnl_cls_put(*args)
rtnl_cls_put = _capi.rtnl_cls_put

def rtnl_cls_add(*args):
  return _capi.rtnl_cls_add(*args)
rtnl_cls_add = _capi.rtnl_cls_add

def rtnl_cls_delete(*args):
  return _capi.rtnl_cls_delete(*args)
rtnl_cls_delete = _capi.rtnl_cls_delete

def rtnl_cls_set_prio(*args):
  return _capi.rtnl_cls_set_prio(*args)
rtnl_cls_set_prio = _capi.rtnl_cls_set_prio

def rtnl_cls_get_prio(*args):
  return _capi.rtnl_cls_get_prio(*args)
rtnl_cls_get_prio = _capi.rtnl_cls_get_prio

def rtnl_cls_set_protocol(*args):
  return _capi.rtnl_cls_set_protocol(*args)
rtnl_cls_set_protocol = _capi.rtnl_cls_set_protocol

def rtnl_cls_get_protocol(*args):
  return _capi.rtnl_cls_get_protocol(*args)
rtnl_cls_get_protocol = _capi.rtnl_cls_get_protocol

def rtnl_htb_get_rate2quantum(*args):
  return _capi.rtnl_htb_get_rate2quantum(*args)
rtnl_htb_get_rate2quantum = _capi.rtnl_htb_get_rate2quantum

def rtnl_htb_set_rate2quantum(*args):
  return _capi.rtnl_htb_set_rate2quantum(*args)
rtnl_htb_set_rate2quantum = _capi.rtnl_htb_set_rate2quantum

def rtnl_htb_get_defcls(*args):
  return _capi.rtnl_htb_get_defcls(*args)
rtnl_htb_get_defcls = _capi.rtnl_htb_get_defcls

def rtnl_htb_set_defcls(*args):
  return _capi.rtnl_htb_set_defcls(*args)
rtnl_htb_set_defcls = _capi.rtnl_htb_set_defcls

def rtnl_htb_get_prio(*args):
  return _capi.rtnl_htb_get_prio(*args)
rtnl_htb_get_prio = _capi.rtnl_htb_get_prio

def rtnl_htb_set_prio(*args):
  return _capi.rtnl_htb_set_prio(*args)
rtnl_htb_set_prio = _capi.rtnl_htb_set_prio

def rtnl_htb_get_rate(*args):
  return _capi.rtnl_htb_get_rate(*args)
rtnl_htb_get_rate = _capi.rtnl_htb_get_rate

def rtnl_htb_set_rate(*args):
  return _capi.rtnl_htb_set_rate(*args)
rtnl_htb_set_rate = _capi.rtnl_htb_set_rate

def rtnl_htb_get_ceil(*args):
  return _capi.rtnl_htb_get_ceil(*args)
rtnl_htb_get_ceil = _capi.rtnl_htb_get_ceil

def rtnl_htb_set_ceil(*args):
  return _capi.rtnl_htb_set_ceil(*args)
rtnl_htb_set_ceil = _capi.rtnl_htb_set_ceil

def rtnl_htb_get_rbuffer(*args):
  return _capi.rtnl_htb_get_rbuffer(*args)
rtnl_htb_get_rbuffer = _capi.rtnl_htb_get_rbuffer

def rtnl_htb_set_rbuffer(*args):
  return _capi.rtnl_htb_set_rbuffer(*args)
rtnl_htb_set_rbuffer = _capi.rtnl_htb_set_rbuffer

def rtnl_htb_get_cbuffer(*args):
  return _capi.rtnl_htb_get_cbuffer(*args)
rtnl_htb_get_cbuffer = _capi.rtnl_htb_get_cbuffer

def rtnl_htb_set_cbuffer(*args):
  return _capi.rtnl_htb_set_cbuffer(*args)
rtnl_htb_set_cbuffer = _capi.rtnl_htb_set_cbuffer

def rtnl_htb_get_quantum(*args):
  return _capi.rtnl_htb_get_quantum(*args)
rtnl_htb_get_quantum = _capi.rtnl_htb_get_quantum

def rtnl_htb_set_quantum(*args):
  return _capi.rtnl_htb_set_quantum(*args)
rtnl_htb_set_quantum = _capi.rtnl_htb_set_quantum

def rtnl_htb_get_level(*args):
  return _capi.rtnl_htb_get_level(*args)
rtnl_htb_get_level = _capi.rtnl_htb_get_level

def addr2obj(*args):
  return _capi.addr2obj(*args)
addr2obj = _capi.addr2obj

def obj2addr(*args):
  return _capi.obj2addr(*args)
obj2addr = _capi.obj2addr

def rtnl_addr_alloc():
  return _capi.rtnl_addr_alloc()
rtnl_addr_alloc = _capi.rtnl_addr_alloc

def rtnl_addr_get(*args):
  return _capi.rtnl_addr_get(*args)
rtnl_addr_get = _capi.rtnl_addr_get

def rtnl_addr_build_add_request(*args):
  return _capi.rtnl_addr_build_add_request(*args)
rtnl_addr_build_add_request = _capi.rtnl_addr_build_add_request

def rtnl_addr_add(*args):
  return _capi.rtnl_addr_add(*args)
rtnl_addr_add = _capi.rtnl_addr_add

def rtnl_addr_build_delete_request(*args):
  return _capi.rtnl_addr_build_delete_request(*args)
rtnl_addr_build_delete_request = _capi.rtnl_addr_build_delete_request

def rtnl_addr_delete(*args):
  return _capi.rtnl_addr_delete(*args)
rtnl_addr_delete = _capi.rtnl_addr_delete

def rtnl_addr_flags2str(*args):
  return _capi.rtnl_addr_flags2str(*args)
rtnl_addr_flags2str = _capi.rtnl_addr_flags2str

def rtnl_addr_str2flags(*args):
  return _capi.rtnl_addr_str2flags(*args)
rtnl_addr_str2flags = _capi.rtnl_addr_str2flags

def rtnl_addr_set_label(*args):
  return _capi.rtnl_addr_set_label(*args)
rtnl_addr_set_label = _capi.rtnl_addr_set_label

def rtnl_addr_get_label(*args):
  return _capi.rtnl_addr_get_label(*args)
rtnl_addr_get_label = _capi.rtnl_addr_get_label

def rtnl_addr_set_ifindex(*args):
  return _capi.rtnl_addr_set_ifindex(*args)
rtnl_addr_set_ifindex = _capi.rtnl_addr_set_ifindex

def rtnl_addr_get_ifindex(*args):
  return _capi.rtnl_addr_get_ifindex(*args)
rtnl_addr_get_ifindex = _capi.rtnl_addr_get_ifindex

def rtnl_addr_set_link(*args):
  return _capi.rtnl_addr_set_link(*args)
rtnl_addr_set_link = _capi.rtnl_addr_set_link

def rtnl_addr_get_link(*args):
  return _capi.rtnl_addr_get_link(*args)
rtnl_addr_get_link = _capi.rtnl_addr_get_link

def rtnl_addr_set_family(*args):
  return _capi.rtnl_addr_set_family(*args)
rtnl_addr_set_family = _capi.rtnl_addr_set_family

def rtnl_addr_get_family(*args):
  return _capi.rtnl_addr_get_family(*args)
rtnl_addr_get_family = _capi.rtnl_addr_get_family

def rtnl_addr_set_prefixlen(*args):
  return _capi.rtnl_addr_set_prefixlen(*args)
rtnl_addr_set_prefixlen = _capi.rtnl_addr_set_prefixlen

def rtnl_addr_get_prefixlen(*args):
  return _capi.rtnl_addr_get_prefixlen(*args)
rtnl_addr_get_prefixlen = _capi.rtnl_addr_get_prefixlen

def rtnl_addr_set_scope(*args):
  return _capi.rtnl_addr_set_scope(*args)
rtnl_addr_set_scope = _capi.rtnl_addr_set_scope

def rtnl_addr_get_scope(*args):
  return _capi.rtnl_addr_get_scope(*args)
rtnl_addr_get_scope = _capi.rtnl_addr_get_scope

def rtnl_addr_set_flags(*args):
  return _capi.rtnl_addr_set_flags(*args)
rtnl_addr_set_flags = _capi.rtnl_addr_set_flags

def rtnl_addr_unset_flags(*args):
  return _capi.rtnl_addr_unset_flags(*args)
rtnl_addr_unset_flags = _capi.rtnl_addr_unset_flags

def rtnl_addr_get_flags(*args):
  return _capi.rtnl_addr_get_flags(*args)
rtnl_addr_get_flags = _capi.rtnl_addr_get_flags

def rtnl_addr_set_local(*args):
  return _capi.rtnl_addr_set_local(*args)
rtnl_addr_set_local = _capi.rtnl_addr_set_local

def rtnl_addr_get_local(*args):
  return _capi.rtnl_addr_get_local(*args)
rtnl_addr_get_local = _capi.rtnl_addr_get_local

def rtnl_addr_set_peer(*args):
  return _capi.rtnl_addr_set_peer(*args)
rtnl_addr_set_peer = _capi.rtnl_addr_set_peer

def rtnl_addr_get_peer(*args):
  return _capi.rtnl_addr_get_peer(*args)
rtnl_addr_get_peer = _capi.rtnl_addr_get_peer

def rtnl_addr_set_broadcast(*args):
  return _capi.rtnl_addr_set_broadcast(*args)
rtnl_addr_set_broadcast = _capi.rtnl_addr_set_broadcast

def rtnl_addr_get_broadcast(*args):
  return _capi.rtnl_addr_get_broadcast(*args)
rtnl_addr_get_broadcast = _capi.rtnl_addr_get_broadcast

def rtnl_addr_set_multicast(*args):
  return _capi.rtnl_addr_set_multicast(*args)
rtnl_addr_set_multicast = _capi.rtnl_addr_set_multicast

def rtnl_addr_get_multicast(*args):
  return _capi.rtnl_addr_get_multicast(*args)
rtnl_addr_get_multicast = _capi.rtnl_addr_get_multicast

def rtnl_addr_set_anycast(*args):
  return _capi.rtnl_addr_set_anycast(*args)
rtnl_addr_set_anycast = _capi.rtnl_addr_set_anycast

def rtnl_addr_get_anycast(*args):
  return _capi.rtnl_addr_get_anycast(*args)
rtnl_addr_get_anycast = _capi.rtnl_addr_get_anycast

def rtnl_addr_get_valid_lifetime(*args):
  return _capi.rtnl_addr_get_valid_lifetime(*args)
rtnl_addr_get_valid_lifetime = _capi.rtnl_addr_get_valid_lifetime

def rtnl_addr_set_valid_lifetime(*args):
  return _capi.rtnl_addr_set_valid_lifetime(*args)
rtnl_addr_set_valid_lifetime = _capi.rtnl_addr_set_valid_lifetime

def rtnl_addr_get_preferred_lifetime(*args):
  return _capi.rtnl_addr_get_preferred_lifetime(*args)
rtnl_addr_get_preferred_lifetime = _capi.rtnl_addr_get_preferred_lifetime

def rtnl_addr_set_preferred_lifetime(*args):
  return _capi.rtnl_addr_set_preferred_lifetime(*args)
rtnl_addr_set_preferred_lifetime = _capi.rtnl_addr_set_preferred_lifetime

def rtnl_addr_get_create_time(*args):
  return _capi.rtnl_addr_get_create_time(*args)
rtnl_addr_get_create_time = _capi.rtnl_addr_get_create_time

def rtnl_addr_get_last_update_time(*args):
  return _capi.rtnl_addr_get_last_update_time(*args)
rtnl_addr_get_last_update_time = _capi.rtnl_addr_get_last_update_time


